## docker-compose.yml
#
#version: '3.8'
#
#services:
#  db:
#    image: postgres:latest
#    container_name: db_app
#    ports:
#      - "5432:5432"
#    env_file:
#      - .env-docker
#
#  app:
#    build: .
#    env_file:
#      - .env-docker
#    container_name: fastapi_app
#    ports:
#      - "7777:8000"
#    depends_on:
#      - db




services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
